# Generated by Django 6.0 on 2025-12-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='angkatan',
            field=models.CharField(max_length=4),
        ),
    ]
