# Generated by Django 6.0 on 2025-12-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_angkatan_alter_profile_kontak_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
