# Generated by Django 6.0 on 2025-12-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_delete_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kontak_wa',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
